name: 'EP/readit/enqueue'

on:
  workflow_dispatch:
    inputs:
      url:
        description: 'URL to enqueue'
        required: true
      # url/ END
    # inputs/ END
  # workflow_dispatch/ END
# on/ END

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      INPUT_URL: ${{ github.event.inputs.url }}
    steps:
      - name: 'Show input url'
        run: echo "$INPUT_URL"

      - uses: actions/checkout@v6

      - uses: astral-sh/setup-uv@v7
        with:
          version: 0.9.22 # Latest as of 2026 Jan 07
        # with/ END

      - name: 'Install server'
        run: uv tool install --force ./

        # TODO Reduce duplication
      - name: 'Fetch'
        env:
          OWNER_TOKEN: ${{ secrets.TOKEN }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          # This variable is used during module loading
          # TODO Find a way to remove this redundant "GEMINI_API_KEY"
          FETCH_FILE: '/tmp/fetch.json'
        run: |
          endpoint-readit-fetch -o "$FETCH_FILE" "$INPUT_URL"
          endpoint-readit-ensure-URL-not-in-eval-queue "$FETCH_FILE"

      - name: 'Enqueue'
        env:
          OWNER_TOKEN: ${{ secrets.TOKEN }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          FETCH_FILE: '/tmp/fetch.json'
          SUMMARY_FILE: '/tmp/summary.json'
        run: |
          endpoint-readit-summarize-other -o "$SUMMARY_FILE" "$FETCH_FILE"
          endpoint-readit-add-summary-to-eval-queue "$SUMMARY_FILE"
          endpoint-readit-send-to-personal "$SUMMARY_FILE"
          endpoint-readit-send-to-queue-v2 "$SUMMARY_FILE"
        continue-on-error: true
        # 'continue-on-error' ensures that a failure from one command not to affect the others
      - name: 'Upload artifacts'
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: readit-artifacts
          path: |
            /tmp/fetch.json
            /tmp/summary.json
          if-no-files-found: ignore
    # steps/ END
  # run/ END
# jobs/ END
