name: 'EP/readit/enqueue'

on:
  workflow_dispatch:
    inputs:
      url:
        description: 'URL to enqueue'
        required: true
      # url/ END
    # inputs/ END
  # workflow_dispatch/ END
# on/ END

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      INPUT_URL: ${{ github.event.inputs.url }}

      # Intermediate files
      FETCH_FILE: '/tmp/fetch.json'
      SUMMARY_FILE: '/tmp/summary.json'
    steps:
      - name: 'Show input url'
        run: echo "$INPUT_URL"

      - uses: actions/checkout@v6

      - uses: astral-sh/setup-uv@v7
        with:
          version: 0.9.22 # Latest as of 2026 Jan 07
        # with/ END

      - name: 'Install server'
        run: uv tool install --force ./

      - name: 'Fetch content'
        run: endpoint-readit-fetch -o "$FETCH_FILE" "$INPUT_URL"

      - name: 'Ensure URL not in eval queue'
        env:
          OWNER_TOKEN: ${{ secrets.TOKEN }}
        run: endpoint-readit-ensure-URL-not-in-eval-queue "$FETCH_FILE"

      - name: 'Summarize content'
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: endpoint-readit-summarize-other -o "$SUMMARY_FILE" "$FETCH_FILE"

      - name: 'Add summary to eval queue'
        env:
          OWNER_TOKEN: ${{ secrets.TOKEN }}
        run: endpoint-readit-add-summary-to-eval-queue "$SUMMARY_FILE"

      - name: 'Send summary'
        env:
          OWNER_TOKEN: ${{ secrets.TOKEN }}
        run: endpoint-readit-send "$SUMMARY_FILE"

      - name: 'Upload artifacts'
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: readit-artifacts
          path: |
            ${{ env.FETCH_FILE }}
            ${{ env.SUMMARY_FILE }}
          if-no-files-found: ignore
    # steps/ END
  # run/ END
# jobs/ END
